version: '3'

services:
  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
      MYSQL_DATABASE: projet
    networks:
      - myavatar
    volumes:
      - ./database-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    links:
      - "db:db"
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_PASSWORD: root
      PMA_USER: root
    networks:
      - myavatar

  maildev:
    image: maildev/maildev
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    networks:
      - myavatar

networks:
  myavatar:
